### ISSUE TITLE
Error: MSBuild not found at "C:\Program Files (x86)\MSBUILD\14.0\Bin\MSBuild.exe"!

### ISSUE THREAD

**Issue by CometRewritten** [TTExtensions/MouseClickSimulator#3]
Hi, I downloaded all the files but when I click build an error comes up saying. 

Error: MSBuild not found at "C:\Program Files (x86)\MSBUILD\14.0\Bin\MSBuild.exe"!

If you know how I can fix this that would be great! Also thank you for developing this soft wear! :)

**Comment by CometRewritten** [comment]
Ok I fixed the first problem but now I am getting this error

-------------------------------------------------------------------------------------
Building the TTR Mouse Click Simulator...

MSBUILD : error MSB1009: Project file does not exist.
Switch: TTMouseclickSimulator\TTMouseclickSimulator.csproj
Press any key to continue . . .

-------------------------------------------------------------------------------------
If you know whats wrong with this I'd really appreciate it.

**Comment by TTExtensions** [comment]
Hi,
that sounds as if the working directory was not the directory of the script.

I have applied a change to BUILD.cmd to fix this. Can you please re-download the repository / ZIP file to see if it has fixed the issue?
Thanks

**Comment by CometRewritten** [comment]
The only difference that time what that my computer asked me if I was sure I wanted to run the program and then this error came up in the cmd.


MSBUILD : error MSB1009: Project file does not exist.
Switch: TTMouseclickSimulator\TTMouseclickSimulator.csproj
Press any key to continue . . .

**Comment by CometRewritten** [comment]
The only difference was that my computer asked me if I was sure I wanted to run the program but the same error came up.

MSBUILD : error MSB1009: Project file does not exist.
Switch: TTMouseclickSimulator\TTMouseclickSimulator.csproj
Press any key to continue . . .

**Comment by TTExtensions** [comment]
Hi,
assuming you downloaded the Zip file (MouseClickSimulator-master.zip), did you extract it? Or did you double-click on it, then double-clicked on the BUILD.cmd file? In the latter case if you don't have a custom Zip program installed, Windows Explorer will just extract that file and run it, so it cannot find the project file.
Instead, you would need to right-click on the .zip file and then select "Extract all..." to extract all of its contents to a folder. Then you can open that folder double-click on the BUILD file.

**Comment by TTExtensions** [comment]
Please reopen the issue if you still have this problem. Thanks
