### ISSUE TITLE
Toontown Not Found

### ISSUE THREAD

**Issue by Jerrikaa** [TTExtensions/MouseClickSimulator#5]
I downloaded the version 25 and when I click it to start, it gives me an error of Toontown not being found even though I have it up and ready to go. Am I doing something wrong?

**Comment by MagwaldJason** [comment]
https://github.com/TTExtensions/MouseClickSimulator/wiki/Running-the-Simulator

Hello, please see the link above. You'll have to download the code as a zip and build it as an exe file to run it on your computer. It sounds like you downloaded the old version (from 2010) that only works with Disney's original Toontown. If you follow the instructions it isn't so hard and doesn't take too long to build. :)

**Comment by TTExtensions** [comment]
Hi, that is correct, Version 25 sounds like the old version for classic TT, which is not compatible with TT Rewritten. (I have now removed the download links to the old version.)
As @MagwaldJason  said, you should be able to build the new version that works with TT Rewritten by following the wiki article.
