### ISSUE TITLE
Donald's DreamLand

### ISSUE THREAD

**Issue by DatAsian** [TTExtensions/MouseClickSimulator#8]
Hi! Your code for all the sample maps you have work flawlessly for me! My only request is if you are able to make one for DDL (Pajama Place or anywhere in DDL would be great). 

I tried to modify one of your codes to make one for Pajama Place, DDL, but I wasn't able to get it to detect the bubbles. How (what programs if any) did you do these specs in the loop?: 
<AutomaticFishing scan1="260, 196" 
scan2="1349, 626" 
bubbleColorRgb="22, 140, 118"
toleranceRgb="13, 13, 15" />

I used an online detect to find the "rgb" of the bubbles, but it still wasn't detecting them. And as for the "scan" I had no clue how to do those. Thanks in advance!

**Comment by TTExtensions** [comment]
Hi,
I added a fishing project for Lullaby Lane in DDL (this was also implemented in the old TT Mouseclick Simulator).

The parameters of the `AutomaticFishing` have following meaning:

- `scan1`, `scan2`: The simulator scans for fishing spots in a rectagngle that is defined by two points. `scan1` defines the upper-left point, `scan2` defines the bottom-right point (pixel coordinates in X, Y form). <br>
Note that the pixel coordinates are witten for a Toontown window with a inner size of 1600 (Width) and 1151 (Height), this was the size of the TT window where I took the screenshots for the old Mouseclick Simulator (that size is defined in [MouseHelpers.cs](https://github.com/TTExtensions/MouseClickSimulator/blob/master/TTMouseclickSimulator/Core/ToontownRewritten/Actions/MouseHelpers.cs)).
- `bubbleColorRgb` specifies the RGB (red, green, blue) color to scan for. E.g. you can take a few screenshots and then examining the color of the fishing bubbles, then use the average values.
- `toleranceRgb` is the max. deviation of RGB values (+ and -) which a pixel can have to still be detected as a fishing bubble.

Hope this helps.
